Change to v23 directory before building
The previous attempt failed with:
pattern ./v23/...: directory prefix v23 does
    not contain main module or its selected dependencies
Error: Process completed with exit code 1.